cc_library(
    name = "remote_signing_server",
    srcs = ["remote_signing_provider.cc"],
    hdrs = [
        "remote_signing_provider.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//common",
        "//hub/crypto",
        "//proto:signing_server_cpp",
    ],
)
