cc_library(
    name = "crypto_provider_api",
    srcs = ["crypto_provider_api.cc"],
    hdrs = [
        "crypto_provider_api.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//common",
        "//hub/crypto",
    ],
)
