cc_library(
    name = "stats",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_google_glog//:glog",
        "@boost//:uuid"
    ],
)
