cc_library(
    name = "stats",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "//common/types",
        "@com_github_google_glog//:glog",
    ],
)
