// Copyright 2018 IOTA Foundation

#include <gtest/gtest.h>

#include <stdexcept>
#include <string>

#include "common/crypto/argon2_provider.h"
#include "common/crypto/types.h"
#include "hub/crypto/local_provider.h"
#include "hub/tests/runner.h"

namespace {

class LocalSigningProviderTest : public hub::Test {};

TEST_F(LocalSigningProviderTest, EnforceMinimumSeedLength) {
  EXPECT_THROW(hub::crypto::LocalSigningProvider{std::string("abcdefg")},
               std::runtime_error);
}

TEST_F(LocalSigningProviderTest, ShouldReturnValidAddress) {
  hub::crypto::LocalSigningProvider provider(std::string("abcdefgh"));
  common::crypto::UUID uuid;
  auto address = provider.getAddressForUUID(uuid).value();

  EXPECT_EQ(address.size(), 81);
}

TEST_F(LocalSigningProviderTest, ConstantAddressForUUID) {
  hub::crypto::LocalSigningProvider provider(std::string("abcdefgh"));
  common::crypto::UUID uuid;
  auto address1 = provider.getAddressForUUID(uuid).value();
  auto address2 = provider.getAddressForUUID(uuid).value();

  EXPECT_EQ(address1, address2);
}

TEST_F(LocalSigningProviderTest, DifferentUUIDsHaveDifferentAddresses) {
  hub::crypto::LocalSigningProvider provider(std::string("abcdefgh"));
  common::crypto::UUID uuid1;
  common::crypto::UUID uuid2;
  EXPECT_NE(uuid1, uuid2);

  auto address1 = provider.getAddressForUUID(uuid1).value();
  auto address2 = provider.getAddressForUUID(uuid2).value();

  EXPECT_NE(address1, address2);
}

TEST_F(LocalSigningProviderTest, CorrectAddress) {
  hub::crypto::LocalSigningProvider provider(
      std::string("abcdefghijklmnopqrstuvwxyz"));
  common::crypto::UUID uuid(
      "43vgLK8NYigfKagfahbCSm+lMFcilNjZyV8Jj6blqX5u98Lx7vjH98AG1oh/ezOR");

  auto address = provider.getAddressForUUID(uuid).value();

  ASSERT_EQ(address.str(),
            "TLGUJV9NKSKKLQYBABOPVINMHRMPOOADQPWGFAFULPVXFQBFDJXQGJVLELQECCIQAX"
            "JCBXKVPDCWYWYQB");
}

TEST_F(LocalSigningProviderTest, CorrectSignature) {
  hub::crypto::LocalSigningProvider provider(
      std::string("abcdefghijklmnopqrstuvwxyz"));
  // seed =
  // TTUVCDOGKVNMAPWDOIZPTBXAJDONMORWUMYWVFNDNYTYQUNREPBHTRVHKAJWXXVTHSRIFSCRGTOGZXPPD
  common::crypto::UUID uuid(
      "43vgLK8NYigfKagfahbCSm+lMFcilNjZyV8Jj6blqX5u98Lx7vjH98AG1oh/ezOR");
  common::crypto::Hash bundleHash(
      "VLZTNAO9IHHDFDKDICSYXWIKZELHMPYKKGHCALIUTKEGNDLCSJGASEMVLGCGIVQSHPCLFRZJ"
      "ZKUOLAAAA");

  std::string expectedSignature =
      "NJCPMNLRFKPCIQSIXQCYOOGLTHSTNGUFPTQOOWLSOOEUGZXCHPNPNLSSCWEL9ZHCWSYLZQRU"
      "TDJFRQJKZZWBOSASC9CGKJNHXEFCYBIKYMHQQBWUDUBJNKUTDZZTWVHQKQXMEIMBXCWIGIUZ"
      "HXGOPOWLDMQAKRKYAWSDGFUNPYECUIEOZJJBIMQYAAXBZPALYEUIMHAWIQRYQKFAGWRQVTWD"
      "R9HQTTC9VSVOBUKPXUNT9BKFXTCQQZLNCXHAZEXZYWUNVQDEOKLVUOCKTDNZDNSLHILBLFBJ"
      "FOYMBFQEUTCDVQTT9NLJTEXRGENDOVNTECMAYCDWOGD9WW9XQTQJKOBUBEBZAFNHNJPYDHPL"
      "JFJTWMJFEEQOQDCULHF9CCTPZWZ9ETRIPJTDVPPWERWTWNQXRCSSNHRDPBEULQ9KMRRXGXY9"
      "STBOAEFKSYDZNJCFQAZVQYDBEZTTSBGPKHQNIKDKSYAPMQIKCUJVUWJQJUEXQTNRHLMWOCHQ"
      "GIDDWATBPEYDWGAKSVHRCCNQQPYTPSYDEWCKHLGYSFFYP9SVPKJLBUPRECYGGCWIESYDCLKS"
      "ODPHUZGNAREWAUYSDRXXSHDGGVOIRPVLJKFRVAHJJLL9UMSRJYBPCDPCLZCNJVIYIJESWLZW"
      "HXHTUGEYCYLLPIXGWJYZOQS9BMAZCBWFYPTXBDJGIXLQKN9RALZXGAIFLVTUBEBDSWODPRON"
      "BOEHIAVUBNV9FUKXYKVAIDUGMPPTMKALS9LCXOLMQHHAISFRUB9YNHGHELRJXJQVQJNXLU9J"
      "AWFPUTCKD9SDQDEX9WUECHEECNZOCWKA9WUWVCKGXLLNIUWLZLT9MK9XMSDHDLFPCPKNITAS"
      "SKSMHBX9YQZALMCJE9NHCACHAVBUZCRMDGIQHRZEKTAVQGJUQSUIDMTIZUEPXHRTGWOJXGIH"
      "B9LRRSQCUESHDSWUKDK9MKEVSEL9MJORY9BXTQKVSA9GVDILOINEUMTVUQENSFETFQI9RJKE"
      "WUQYT9BWQINVEPNYMMJPDVIRXQL9IRBS9KNUDTRCHHLACSTHNMJFKFPKADUINVULJVIHVTJF"
      "WJ9EKNKDPILPU9LV9YUTLJYMCBYRWFCIHSWDNEUUYCNAXNMDQVYAHAEEEVJHX99KQ9RHMRTQ"
      "EKOSLXKXLOEXVYFQABHVNSCORW9XVZLNUD9MCGEIGXZLKHAAWFTFH9NSWMOCQNXFFGTJOPHG"
      "MTQS9RBOWGZRQPDIUVSBSNWURRZUGOC9YUSOXVLBNBXFAAGWJMJLWGJSRYABDGRHNBM9GDED"
      "LMDRLUYXMKJ9CTHBVAJPKU9QFTMPLJVPS9YLBKKJLSGYHDOFT99PTNNAQINUCDUQZZUVGBTJ"
      "JBPAXVRRDFPXR9ZTUADZXFGHMOFACPHLYGUKYBGRTCOJGNUPTVEMQSNENWLKNKQWYQNYYTYS"
      "AZBOJCUFJUHVBUJHFWN9SGMJNKVOHDNSDQLYXYUXB9LBOGL9QXOIIPBJJHWXUGZTIUGJFBYT"
      "JUSQY9LWHBMORDACTKOQSDNKRAWDAZVFBRVO9OXTQ99NYBMNKBTVVASYWEAM9NEONYZ9DRNU"
      "DOJSZYFDPXDTVFCSMOOBRSRSMTOESJXZNVOCQBFUFRDUZPMVSCBNIYSEGDQHXDUCQHCT9RTY"
      "JUELKZPDSBKUXQTXLADEXIHNZAHODG99WCNSCPWSDFYGCECVHVMSLYUXWVZKFVYPNKQSGJHK"
      "CIDKNYJSGLDKSPFCFTJFAYNTAUIOYPCVKUWKDCLSCE9KUVPZAAQ9BDVKMABZHPKTLMYLZOAU"
      "DFISWPPUKZRZMGYKACUDTD9MCJUYKKQIBRQHVIDRONCUEXVXTKMWHKFNOCZVVJCDQBOAZWGA"
      "9CZM9WCSBZFHBPOQNBTMNSVMWIDWSBLRTUIUWUBULEQI9HJJAYUYPJJFWZEIXCHQGBPHHSEZ"
      "XWNK9NLZTWJEOTZBJVPAYKUKCFGKNQO9JCQFOEOPGOEHGWYENEBE9TRUL9UYAADTUWQHABQY"
      "SHMRDVR9CNOV9GBBLYL9XHZEMEIBILQ9WA9AYYLKXTXUOJPNLOYAKXDUXVJSJWKSEJUDEMWQ"
      "NINPLBOHUASIFTBUOBW9GMURA9GSIX9ZIDQTX9FGOUWU9L9LWUOBHSA9KGQSVQWQHRYJMUJT"
      "LOFIAAAGGXRSILILSSZHWJHA9FCZHSF9IWWMKGZGFR9NRBEHPZPOLAZCVHGNSOWEJPPQICQR"
      "GR9WMVDEUPXQJRHYFXTHLOYZS9ZDTUGY9JAXXIBVUJRNUDJDSXCOSA9T9EPTFCBVZCMNFWMN"
      "SYTZPFBPVPNOCXHCYQFDKCBJC9STPVRAFAZQICXTTKDW9KLIKUVKQWYJKVFWERMVLIPVBVMI"
      "CM9ZUMCDRQZGMGRGXZJPJWTNGLRICEYTSOTPIZZXUEAHNJCVWMWQOXILIOGVGRKXUGZGWYRJ"
      "RRQRPHCWKZKASBQVDZUH9JH99VTAXNYFCPYZAYYGYYOIRDTAPCAIDXGDLSLRO9WWAWMHKFCE"
      "DVPKANOKHMHXRCEGIPCJTQVAQNQYFKTDTJYNHFUQGXRLXBUDPJXKXTBTSCHVTMRVNHBLQU9D"
      "VCMFQGVFKSTPLGNUY9LAHLCXSOXUZZASPLYHB9UWSLUAVPZKLLNIWKOYYVQYP9DMPBCH9IMF"
      "STRHOJTHYUPRUUNRNMMOPM9FTBI9LHWBDIFWNDRTBSJWRHVUYQ9KMLMYWOARSXQDKASKHUFJ"
      "BTEXHNFZHKKJBCFUBZGNBHIBWIKSGXDVIHCSZCMDYQTGFMVOLHOUE9BXNBMPRC9PBKRSVVXN"
      "GRCSXJLDOVFOZYKXZXSFOZKRHAXEBQAZIJD9YWECQXV9ZNEOHKVNSKUFEDWDYIUQTUDHRMEL"
      "SDARBHLEQGAHMKJFWJ9GFMQPSTNAMHQUOZW9YDTVFOW9ADGASYWJVCJAKDPKJBSC9O9LTNLV"
      "VTIERDZNTSGZPAMPFXYSJRADHDYDTDTF9OAFB9UBCFJ9AYOKGVQNIMZEBHSWDVUZXKDGWNYX"
      "YKJCEBRFWIKYKUVBIOSNVXQHFPSSQWXAOBIYSHSNPLSLY9SVXPHYVAVESSFIOBPVNFWGMRHM"
      "CNZCKIKNVWAXENHR9GKIYCFAEHUETPKFSGMIWCXBUEGZFI9YJKNQISQRI9GBFWZXOQT9ILQW"
      "SEAKTQZRQM9IX9VGNYUVDNDJZLNRGEVTSASOWRLWMSHSXCDZDPSZOWWNH9M9JDJB9EGOBLX9"
      "VQJROKTFWSHBX9WJNDNQQGLQKMCNXNUBRSKVGPBIQYEYLLMTC9EALUYPITIGDVERLYSSZBGX"
      "DUDPGJWXZGEITTTEIABYKSTLNJHZHELNSRPEDLCD9SWRKKOVMUQ9YYS9ACEMPSLZCOFMWSUF"
      "PTFISIGZY9DHMDMGJXCXDYARGCN9IPHAPDRPTIOOFNCEGKVNUCLLBKCV9VV9VQUTIPMSDAYE"
      "FIMEENVHDGPXTKKQMNBYCORWJYDUOPSBXPFMOJQORQOFWNZBUVMBOJQNLYWLNNAXTJOQ9XSI"
      "DWFOKUUQZHKHKUQDIBPIPIB9JOMIAABJLOVCLAIYQIXDXUKXRYYBKBTGMEXRRGGYFFXEBERH"
      "YKZOGFMOMLIUJIUYBSB9LCKLJZXXWLMYUMARUM9YOYLACMNCQLUG9JFXTAEUAIZHT9JMWSYY"
      "OEQZVLKKDPYGDDWJHAUTQDLIVIOKKFUGBRWCBTJZLZHHWLCTJYPMACLAJOICGCMUNKGSLNTP"
      "KGOITTTHHHHXROBYFBGDJBOU9WPCFOQOYHTQRMTFADBALWGEDMVNMATERFL9PLZNOGUCMXQP"
      "JYBPKJKVKRIPWE9ROLILTDFNNBZZIOVIHMOZPCIQEEJYJSTDFVWVOQRDZFGZESTNLTUOZONB"
      "AKKTKCXMXPNWHXGNALJRSSTYKYTULXPWEXNKIQGEFZXSPSNPC9NSBRCNKFJSSI9ZTJEUWGRA"
      "FFNLFGPOZHHRIOILRY9EEJUE9KARXPLU9FUPDBFWCNGTQKIUUOXSIEPRPONLMJBRBVYDIJVR"
      "OLMNCDLAELQETMZQCWB9YMWOLYLASVIGZOQIL99OMHLCALCOOTHWEK9MXQSIUCEPRDDOI9YB"
      "UUGKEXAOSYEEBNQWMTTG9YX9UBXAUGDIJFFJQQDBVDNEIHXNBNWQXF9WAILTKYR9SEQBKNMM"
      "DADNNVAWNIFGKXWYJFSVOJXPUAACIXDDBGGYTASGHQUFITIQQPLKGBFYHYLEQZZNIHILCL9F"
      "CHYPRQKMYMQB9JKYXENQUADITVQAKLGXWRCSAMOEVY9B9FPLIZGTLCULSERQLBQXATTMHRBB"
      "POVDTQVLSKPTFCDDVOUXDIVDSBEEBUILMYHZIXGHQFNMWUPGGZVLIW";

  auto signature = provider.getSignatureForUUID(uuid, bundleHash).value();

  EXPECT_EQ(signature, expectedSignature);
}

TEST_F(LocalSigningProviderTest, ShouldOnlySignOnce) {
  hub::crypto::LocalSigningProvider provider(std::string("abcdefgh"));
  common::crypto::UUID uuid;

  // First time should work.
  provider.getSignatureForUUID(
      uuid,
      common::crypto::Hash("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                           "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"));

  // Second time should fail.
  ASSERT_THROW(provider.getSignatureForUUID(
                   uuid, common::crypto::Hash(
                             "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
                             "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")),
               std::exception);
}

};  // namespace
