cc_binary(
    name = "hub",
    srcs = ["main.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//hub/db",
        "//hub/server",
        "@com_github_gflags_gflags//:gflags",
        "@com_github_google_glog//:glog",
    ],
)
